log_format "%p %t %l [%i %s] (%c) %m\n"
daemonize yes
pid_file "/tmp/odyssey.pid"
log_file "/tmp/odyssey.log"
log_to_stdout no
locks_dir "/tmp"
workers 2
resolvers 1
nodelay yes
keepalive 7200

listen {
    host "127.0.0.1"
    port 6433
    backlog 256
}

storage "postgres_server" {
    type "remote"
    host "127.0.0.1"
    port 5432
}

database "thai" {
    user "postgres" {
        authentication "scram-sha-256"
        password "admin123#"
        storage "postgres_server"
        storage_password "admin123#"
        pool "transaction"
        pool_size 8
        client_max 1000
    }
}
